apiVersion: v1 
kind: Service 
metadata: 
  name: hostnames 
spec: 
  selector: 
    app: hostnames 
  ports: 
  - name: default 
    protocol: TCP 
    port: 80 
    targetPort: 9376 
  externalIPs: 
  - bb00::2